<#
.SYNOPSIS
  Prepares DeepSeek Excel: checks Node, installs dependencies, and fills in .env.

.DESCRIPTION
  API key lookup order:
    1. the -ApiKey parameter
    2. the DEEPSEEK_API_KEY environment variable
    3. DSH credentials in ~/.dsh/.credentials.yaml (refs.DEEPSEEK_API_KEY)
    4. manual input (Read-Host, hidden)
  The key is never displayed; only the masked form (sk-abc…wxyz).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts/setup.ps1
#>
[CmdletBinding()]
param(
  [string]$ApiKey,
  [string]$Model = 'deepseek-flash',
  [string]$CredentialsFile,
  [switch]$Force,
  [switch]$NonInteractive
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $projectRoot '.env'

function Write-Step($text) { Write-Host "==> $text" -ForegroundColor Cyan }
function Write-Ok($text) { Write-Host "    $text" -ForegroundColor Green }
function Write-Warn2($text) { Write-Host "    $text" -ForegroundColor Yellow }

function Get-MaskedKey([string]$key) {
  if ([string]::IsNullOrWhiteSpace($key)) { return '(empty)' }
  if ($key.Length -le 8) { return '****' }
  return $key.Substring(0, 3) + '…' + $key.Substring($key.Length - 4)
}

function Get-KeyFromDsh {
  $keyScript = Join-Path $PSScriptRoot 'dsh-key.ps1'
  $candidates = @()
  if ($CredentialsFile) { $candidates += $CredentialsFile }
  $candidates += @(
    (Join-Path $HOME '.dsh\.credentials.yaml'),
    (Join-Path $HOME '.dsh\credentials.yaml')
  )
  foreach ($file in $candidates) {
    if (-not (Test-Path $file)) { continue }
    $value = & $keyScript -Path $file -Raw
    if ($LASTEXITCODE -eq 0 -and $value) {
      return @{ Key = ($value | Select-Object -First 1).Trim(); Source = $file }
    }
    Write-Warn2 "No raw DEEPSEEK_API_KEY in $file (likely only a reference)."
  }
  return $null
}

function Read-DotEnv([string]$path) {
  $map = @{}
  if (-not (Test-Path $path)) { return $map }
  foreach ($line in (Get-Content -LiteralPath $path)) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
    $idx = $trimmed.IndexOf('=')
    if ($idx -lt 1) { continue }
    $map[$trimmed.Substring(0, $idx).Trim()] = $trimmed.Substring($idx + 1).Trim()
  }
  return $map
}

function Write-DotEnv([string]$path, [hashtable]$values) {
  $order = @(
    'DEEPSEEK_API_KEY', 'DEEPSEEK_MODEL', 'DEEPSEEK_BASE_URL', 'PORT',
    'MAX_CELLS_PER_WRITE', 'MAX_CELLS_PER_READ', 'MAX_TOOL_ITERATIONS', 'MOCK_LLM', 'DEBUG_LOG'
  )
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# Generated by scripts/setup.ps1 - do not share.')
  $lines.Add('')
  foreach ($key in $order) {
    if ($values.ContainsKey($key)) { $lines.Add("$key=$($values[$key])") }
  }
  foreach ($key in $values.Keys) {
    if ($order -notcontains $key) { $lines.Add("$key=$($values[$key])") }
  }
  Set-Content -LiteralPath $path -Value ($lines -join "`n") -Encoding UTF8
  try {
    $user = "$env:USERDOMAIN\$env:USERNAME"
    & icacls $path /inheritance:r /grant:r "${user}:(R,W)" | Out-Null
    Write-Ok ".env permissions restricted to $user."
  } catch {
    Write-Warn2 "Could not restrict the .env ACL: $($_.Exception.Message)"
  }
}

Write-Step "Checking Node.js"
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) { throw 'Node.js is not installed. Install Node.js 20+ from https://nodejs.org then run this script again.' }
$nodeVersion = (& node -v).TrimStart('v')
$major = [int]($nodeVersion.Split('.')[0])
if ($major -lt 20) { throw "Node.js $nodeVersion is too old; version 20 or newer is required." }
Write-Ok "Node.js v$nodeVersion detected."

Write-Step "Installing dependencies (express, office-addin-dev-certs)"
$npm = Join-Path (Split-Path -Parent $node.Source) 'npm.cmd'
if (-not (Test-Path $npm)) { $npm = 'npm.cmd' }
Write-Warn2 "Using $npm (npm.ps1 is blocked by the AllSigned execution policy on this machine)."
Push-Location $projectRoot
try {
  & $npm install --no-audit --no-fund
  if ($LASTEXITCODE -ne 0) { throw "npm install failed (exit $LASTEXITCODE)." }
} finally {
  Pop-Location
}
Write-Ok 'Dependencies ready.'

Write-Step 'Preparing .env'
$existing = Read-DotEnv $envPath
$key = $null
$source = $null

if ($ApiKey) { $key = $ApiKey.Trim(); $source = '-ApiKey parameter' }
elseif ($existing.ContainsKey('DEEPSEEK_API_KEY') -and $existing['DEEPSEEK_API_KEY'] -and -not $Force) {
  $key = $existing['DEEPSEEK_API_KEY']
  $source = 'the existing .env'
}
elseif ($env:DEEPSEEK_API_KEY) { $key = $env:DEEPSEEK_API_KEY.Trim(); $source = 'environment variable' }
else {
  $found = Get-KeyFromDsh
  if ($found) { $key = $found.Key; $source = $found.Source }
}

if (-not $key) {
  if ($NonInteractive) {
    Write-Warn2 'No API key found in the DSH credentials; non-interactive mode so manual input is skipped.'
  } else {
    Write-Warn2 'No DeepSeek API key found in the DSH credentials.'
    $secure = Read-Host -Prompt 'Paste the DeepSeek API key (Enter to skip)' -AsSecureString
    if ($secure.Length -gt 0) {
      $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
      try { $key = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr) } finally { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
      $key = $key.Trim()
      $source = 'manual input'
    }
  }
}

if ($key) {
  $existing['DEEPSEEK_API_KEY'] = $key
  Write-Ok "API key taken from $source → $(Get-MaskedKey $key)"
} else {
  Write-Warn2 'Without an API key the sidebar can open but cannot call DeepSeek.'
  if (-not $existing.ContainsKey('DEEPSEEK_API_KEY')) { $existing['DEEPSEEK_API_KEY'] = '' }
}

if (-not $existing.ContainsKey('DEEPSEEK_MODEL') -or -not $existing['DEEPSEEK_MODEL']) { $existing['DEEPSEEK_MODEL'] = $Model }
if (-not $existing.ContainsKey('DEEPSEEK_BASE_URL')) { $existing['DEEPSEEK_BASE_URL'] = 'https://api.deepseek.com' }
if (-not $existing.ContainsKey('PORT')) { $existing['PORT'] = '3000' }
if (-not $existing.ContainsKey('MAX_CELLS_PER_WRITE')) { $existing['MAX_CELLS_PER_WRITE'] = '5000' }
if (-not $existing.ContainsKey('MAX_CELLS_PER_READ')) { $existing['MAX_CELLS_PER_READ'] = '2000' }
if (-not $existing.ContainsKey('MAX_TOOL_ITERATIONS')) { $existing['MAX_TOOL_ITERATIONS'] = '12' }
if (-not $existing.ContainsKey('MOCK_LLM')) { $existing['MOCK_LLM'] = '0' }
if (-not $existing.ContainsKey('DEBUG_LOG')) { $existing['DEBUG_LOG'] = '0' }

Write-DotEnv $envPath $existing
Write-Ok ".env written: $envPath (model: $($existing['DEEPSEEK_MODEL']))"

Write-Step 'Next steps'
Write-Host @'
    1. Start the server : npm start
    2. Register add-in  : powershell -ExecutionPolicy Bypass -File scripts/sideload.ps1
    3. Close and reopen Excel, then click the "DeepSeek" button on the Home tab.
    4. Optional (automatic server at login):
       powershell -ExecutionPolicy Bypass -File scripts/autostart.ps1
'@ -ForegroundColor Gray
